[build]
  command = "npm run build"
  publish = ".next"

# Redirección principal para SSR (Next.js)
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next"
  status = 200

# API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/next"
  status = 200
