[build]
  command = "npm run build"
  publish = ".next"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Manejo de rutas para autenticación
[[redirects]]
  from = "/login"
  to = "/auth/login"
  status = 301

[[redirects]]
  from = "/dashboard"
  to = "/dashboard"
  status = 200
  force = true

# Manejo de rutas de autenticación de terceros
[[redirects]]
  from = "/auth/*"
  to = "/auth/:splat"
  status = 200

# Manejo de rutas de la API
[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200

# Redirección para SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
